import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/introduction",
        "getting-started/installation",
        "getting-started/environment",
        "getting-started/deployment",
      ],
    },
  ],

  backendSidebar: [
    {
      type: "category",
      label: "Backend",
      collapsed: false,
      items: [
        "backend/architecture",
        "backend/authentication",
        "backend/authorization",
        "backend/data-model",
        "backend/search-and-pagination",
        "backend/tmdb-integration",
      ],
    },
  ],

  frontendSidebar: [
    {
      type: "category",
      label: "Frontend",
      collapsed: false,
      items: [
        "frontend/overview",
        "frontend/admin-panel",
        "frontend/public-site",
      ],
    },
  ],

  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api-reference",
    },
  ],
};

export default sidebars;
