import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: "category",
      label: "Guide",
      items: [
        "guide/introduction",
        "guide/installation",
        "guide/environment",
        "guide/architecture",
        "guide/authentication",
        "guide/authorization",
        "guide/data-model",
        "guide/search-and-pagination",
        "guide/tmdb-integration",
        "guide/deployment",
      ],
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api-reference",
    },
  ],
};

export default sidebars;
